version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    links:
      - evcc

  evcc:
    image: evcc/evcc
    ports:
      - "7070:7070"
    
